org: skillrank1
app: design-template
service: design-template

provider:
  name: aws
  httpApi:
    cors:
      allowedOrigins:
        - https://6a7777a2099a2b52c44a7dc4--ui-design-principles.netlify.app/
        - http://localhost:3000
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true
      maxAge: 86400
  runtime: python3.14
  region: eu-west-2
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  environment:
    MONGODB_URI: ${ssm:/design-template/${sls:stage}/mongodb-uri}
    MONGODB_DB: ${ssm:/design-template/${sls:stage}/mongodb-db, 'app'}

layers:
  pymongoDependency:
    path: layers/common
    name: ${self:service}-${sls:stage}-pymongo
    compatibleRuntimes:
      - python3.14
    compatibleArchitectures:
      - arm64

functions:
  hello:
    handler: src/api/handler.hello
    package:
      patterns:
        - "!src/**"
        - "!./**"
        - src/api/**
        - src/db.py
        - src/__init__.py
    layers:
      - !Ref PymongoDependencyLambdaLayer
    events:
      - httpApi:
          path: /
          method: get

  createTheme:
    handler: src/api/themes.create
    package:
      patterns:
        - "!src/**"
        - "!./**"
        - src/api/**
        - src/models/**
        - src/services/**
        - src/db.py
        - src/__init__.py
    layers:
      - !Ref PymongoDependencyLambdaLayer
    events:
      - httpApi:
          path: /themes
          method: post
  getTheme:
    handler: src/api/getTheme.lambda_handler
    package:
      patterns:
        - "!src/**"
        - "!./**"
        - src/api/**
        - src/models/**
        - src/services/**
        - src/db.py
        - src/__init__.py
    layers:
      - !Ref PymongoDependencyLambdaLayer
    events:
      - httpApi:
          path: /themes/{slug}
          method: get

  getThemes:
    handler: src/api/getThemes.lambda_handler
    package:
      patterns:
        - "!src/**"
        - "!./**"
        - src/api/**
        - src/models/**
        - src/services/**
        - src/db.py
        - src/__init__.py
    layers:
      - !Ref PymongoDependencyLambdaLayer
    events:
      - httpApi:
          path: /themes
          method: get

  getThemeSlugs:
    handler: src/api/getThemeSlugs.lambda_handler
    package:
      patterns:
        - "!src/**"
        - "!./**"
        - src/api/**
        - src/models/**
        - src/services/**
        - src/db.py
        - src/__init__.py
    layers:
      - !Ref PymongoDependencyLambdaLayer
    events:
      - httpApi:
          path: /themes/slugs
          method: get

custom:
  scripts:
    hooks:
      before:package:initialize: chmod +x ./installLayers.sh && ./installLayers.sh
